// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqJsqejNtrMvGmdfOfbd4asxgTJvMrl10',
    appId: '1:976791735994:web:fd93712030de2325d93c83',
    messagingSenderId: '976791735994',
    projectId: 'workforce-managment-d43b9',
    authDomain: 'workforce-managment-d43b9.firebaseapp.com',
    storageBucket: 'workforce-managment-d43b9.firebasestorage.app',
    measurementId: 'G-TP4HJ34NGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuuGIy_ucv3KbSLYN3AFGXp_3bzG8cgOk',
    appId: '1:976791735994:android:b67cf15312553c91d93c83',
    messagingSenderId: '976791735994',
    projectId: 'workforce-managment-d43b9',
    storageBucket: 'workforce-managment-d43b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDUWGYPmX02X9-JWhmDOL0niwt0Kd0FxM',
    appId: '1:976791735994:ios:13a7995bd730a32fd93c83',
    messagingSenderId: '976791735994',
    projectId: 'workforce-managment-d43b9',
    storageBucket: 'workforce-managment-d43b9.firebasestorage.app',
    iosBundleId: 'com.example.tryzxWorkfoceMangment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqJsqejNtrMvGmdfOfbd4asxgTJvMrl10',
    appId: '1:976791735994:web:ccdcec06bc0ab083d93c83',
    messagingSenderId: '976791735994',
    projectId: 'workforce-managment-d43b9',
    authDomain: 'workforce-managment-d43b9.firebaseapp.com',
    storageBucket: 'workforce-managment-d43b9.firebasestorage.app',
    measurementId: 'G-SXGKKTGTND',
  );
}
